# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45af56e53c9c658358c0653035541a2616aa6a3490ce3758e0163dff5621e2e98b943ff64203e09170d55e17498b9d0ef0e052a4205aa32cabbec7b2dfb976bc

test:
  secret_key_base: 587d37283b619b57f740501ff220d454d9a1418aed8893b298651b06884c5d37e281c9c2d8e490bcf79a4ac31299e6a9557567ee350cf86399b492a6553bdfe1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
